server:
  port: 8080

spring:
  config:
    import: optional:file:sensor-analyzer/.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: sensor-storage-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.example.sensoranalyzer.models
        spring.json.value.default.type: com.example.sensoranalyzer.models.SensorData
      auto-offset-reset: earliest
  application:
    name: sensor-storage