server:
  port: 8082

spring:
  config:
    import: optional:file:sensor-analyzer/.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:5432/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
  jpa:
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: sensor-data-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.sensoranalyzer.models
        spring.json.value.default.type: com.example.sensoranalyzer.models.SensorData
      auto-offset-reset: earliest
  application:
    name: sensor-analyzer

sensor:
  kafka:
    topics:
      temperature: sensor-temperature-topic
      voltage: sensor-voltage-topic
      power: sensor-power-topic